### ISSUE TITLE
The creation of the socket has failed

### ISSUE THREAD

**Issue by HryGan404** [maxtamoian/icmpups#1]
https://github.com/makstamoian/ping/blob/dc3401eb1abb3dee4a2a1fabf486395b5e47c900/main.cpp#L139

The socket creation failed when using SOCK_DGRAM, but it functioned properly with SOCK_RAM.

**Comment by makstamoian** [comment]
Hey! Thanks for the feedback!
It worked on my machine. I'm not quite sure what you mean by "SOCK_RAM". I wasn't able to find a socket type identified as SOCK_RAM:

> /*Standard socket types */
#define  SOCK_STREAM             1 /*virtual circuit*/
#define  SOCK_DGRAM              2 /*datagram*/
#define  SOCK_RAW                3 /*raw socket*/
#define  SOCK_RDM                4 /*reliably-delivered message*/
#define  SOCK_CONN_DGRAM         5 /*connection datagram*/

Although I think you may have meant the `SOCK_RAW` socket type. Since `SOCK_RAW` provides direct access to lower-level communication protocols, it requires root access. But since we don't need any advanced functionality in this specific case (we may need it in [traceroute](https://github.com/makstamoian/traceroute/) though), it's more convenient to use `SOCK_DGRAM`.

`SOCK_DGRAM` is commonly used for short messages, such as ICMP ones, since the order and reliability of message delivery is not guaranteed.

_Here's the screenshot of my machine successfully running ping (former icmpups)_

![Screenshot from 2024-03-26 17 36 18](https://github.com/makstamoian/ping/assets/99553497/0c08b700-2197-4c3f-8970-a0380fa420bf)

**Comment by HryGan404** [comment]
Sorry, actually I mean SOCK_RAW, my computer is Ubuntu 23.10 and Kernel version is 6.6.20. I have to use SOCK_RAW in order to create socket with ICMP protocol, and I also need to give the program `cap_net_raw` or run it in sudo.
Thanks for your feedback, I learned a lot.

**Comment by makstamoian** [comment]
No problem. Feel free to contribute)
